llm:
  provider: openai
  api_key: ${OPENAI_API_KEY}
  model: gpt-4
  max_tokens: 2000
  temperature: 0.7

memory:
  provider: redis
  url: ${REDIS_URL}
  ttl: 3600

tools:
  web_search:
    enabled: true
    api_key: ${SEARCH_API_KEY}
    max_results: 10
  
  data_analysis:
    enabled: true
    max_rows: 100000
    use_gpu: true

plugins:
  market_research:
    enabled: true
    update_frequency: 86400
  
  content_optimizer:
    enabled: true
    metrics:
      - readability
      - engagement
      - seo

execution:
  max_parallel_tasks: 5
  timeout: 300
  retry_attempts: 3